modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/xbony2/Long-Fall-Boots"

[[mods]]
	modId="longfallboots"
	version="${file.jarVersion}"
	displayName="Long Fall Boots"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/long-fall-boots"
	authors="NanoHeart, Xbony2, Chloe Dawn"
	description='''This mod adds Long Fall Boots, so you can jump from any distance and be a-okay!'''

[[dependencies.longfallboots]]
	modId="minecraft"
	mandatory=true
	versionRange="[[1.18,]"
	side="BOTH"

[[dependencies.longfallboots]]
	modId="forge"
	mandatory=true
	versionRange="[39,)"
	side="BOTH"
